[package]
name = "voidpet_graphql_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { features = ["blocking"] }
scraper = "*"
rslint_parser = "*"
cached = "*"
lazy_static = "*"